### PR TITLE
Fix HasBackgroundImageValidator

### PR DESCRIPTION
**Pull request by sabrinefk13**
The background image is required (https://github.com/Setono/SyliusGiftCardPlugin/issues/98)

### CODE REVIEW

**Comment by Roshyo** [comment]
Hi, and thank you for your PR :) 

There is just an issue that would be raised in the PDF : 

```
background: transparent url("{{ path }}") no-repeat left bottom;
```
And `path` would not be defined. SO we should just do a :

```
{% set path = '' %}
```
in the beginning of the template to fix that.

Can you take care of that @sabrinefk13 ?

**Comment by sabrinefk13** [comment]
Hi, @Roshyo 
I have already tested to put the 
{% set path = '' %}
but it does not work :(

**Comment by Roshyo** [comment]
What do you mean ?
The problem that I see here is that with your change on the validator, the backgroundImage can be null when generating the PDF.
If so, the variable `path` won't be defined in Twig, and when it will be called, it will simply crash. Won't it ?
So we need to make sure it is at least defined : 

```
{% set path = '' %}
{% if configuration.backgroundImage is not empty %}
    {% set path = configuration.backgroundImage.path|imagine_filter('setono_sylius_gift_card_background') %}
{% endif %}
```

**Review by Roshyo — APPROVED** [review]

**Comment by Roshyo** [comment]
Thank you @sabrinefk13 !

**Comment by loevgaard** [comment]
Released in `v0.10.1` :)

**Pull request merged**
