### PR TITLE
Add support for PHP 8 attributes in Trait

### PR DESCRIPTION
**Pull request by vasilvestre**
Tested in my own project

### CODE REVIEW

**Comment by loevgaard** [comment]
I have never tried this 'mixing' of attributes and annotations. Does this work without any problems?

**Comment by vasilvestre** [comment]
> I have never tried this 'mixing' of attributes and annotations. Does this work without any problems?

I've tried it locally and had no issue with annotation. I haven't tested both cases

**Comment by loevgaard** [comment]
Hi, @vasilvestre. Can you rebase this on `0.12`? Then we will merge it. Thank you 🎉

**Comment by vasilvestre** [comment]
Done ! Sorry for the delay

**Comment by vasilvestre** [comment]
I don't know why the CI is failing, the symbol is recognized to my IDE in similar settings and wkhtmltopdf seemed to be a temporary bug 😓 
If someone wish to reopen, feel free

**Pull request closed without merging**
